# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
build_backend_from:
  aarch64: golang:1.22-alpine3.18
  arm64: golang:1.22-alpine3.18
  armhf: golang:1.22-alpine3.18
  amd64: golang:1.22-alpine3.18
  armv7: golang:1.22-alpine3.18
  i386: golang:1.22-alpine3.18
  
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Donetick add-on"
  org.opencontainers.image.description: "Simplify Tasks & Chores, Together."
  org.opencontainers.image.source: "https://github.com/Donetick/hassio-addons"
  org.opencontainers.image.licenses: "GNU AFFERO GENERAL PUBLIC LICENSE"
args:
  TEMPIO_VERSION: "2021.09.0"
