# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Donetick Addon
version: "0.0.2"
slug: Dontetick
description: Simplify Tasks & Chores, Together.
url: "https://github.com/Donetick/hassio-addons/tree/main/donetick"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
ports:
  80/tcp: 80
  2021/tcp: 2021
ingress_port: 80
image: "ghcr.io/donetick/{arch}-hassio-addons"
