# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Donetick Addon
version: "0.0.1"
slug: Dontetick
description: Simplify Tasks & Chores, Together.
url: "https://github.com/donetick/addon-hassio/tree/main/donetick"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/donetick/{arch}-hassio-addons"
